### ISSUE TITLE
Order and names of coordinates given by wicket.

### ISSUE THREAD

**Issue by edzer** [ropensci/wicket#15]
Wicket names its result coordinates `lat` and `lng`:
```
> wkt_centroid("POLYGON((0 85,120 85,240 85,0 85))")
  lat lng
1  85   0
```
The naming suggests geographical coordinates (where the programming assumes cartisian, see #14) which doesn't have to be the case; more serious: using the order lat lng contrasts the order in which coordinates are entered in WKT. Why not use lng lat, or simply x y?

**Comment by Ironholds** [comment]
I'll use lng lat, then.

On the general point ("why does the package make these assumptions?") the answer is: because for the package's use case, those are not assumptions. The package was designed to be used within other rOpenSci packages that require (say) basic validation, or handle coordinate data and need the points extracted, or..so on and so forth. This is why it's such a hodegepodge of very general and very specific functionality; because it is responding to specific use cases.

**Comment by sckott** [comment]
to reiterate - oliver is making this for us as a lite weight WKT tool set for use in other packages - many web services allow WKT to delimit a spatially constrained query, and we don't really need a full fledged spatial package for that - so it's not trying to be the best most general purpose thing - striving for solving the use cases we need to solve, and being a lite weight dep. for other packages

**Comment by Ironholds** [comment]
Nicely put!

**Comment by edzer** [comment]
Good to know that Oliver is not making this for us, but please, when you want to reinvent the wheel make sure it's round.

**Comment by Ironholds** [comment]
Well, given that I opened this by saying I'd fix the issue...I am? And will add a clarifying note to the README and DESCRIPTION, along with the contributor code of conduct.

**Comment by edzer** [comment]
@Ironholds when I find 3 wicket issues in 5 minutes, it worries me. Luckily, @sckott says this is for you, not for us, so I shouldn't. 

Despite that, you advertise that "wicket makes WKT reading easier in R", is incredibly fast, and now that it is more portable. We solved portability issues in the past with rgdal and rgeos, and now again with sf, and we also solved the travis issues. I made a speed comparison [here](https://gist.github.com/edzer/29d10b133bba2df9f768e427bc50b098), and would be interested to what you made all your comparisons, and how you did that. The dll created by wicket weights more than that of sf:
```
-rwxrwxr-x  1 edzer edzer 5783368 Jan 22 19:54 wicket.so
-rwxrwxr-x  1 edzer edzer 3959192 Jan 20 16:48 sf.so
```
I'm just curious.

**Comment by sckott** [comment]
@edzer this is an early version, we never said it was perfect

**Comment by okeyes-r7** [comment]
Hey Edzer,

I'm at work right now so won't be paying much attention to this repository but thought I'd address a few things.

First, in terms of reinvention, a bit on the history of this package. Scott proposed I develop it for some of rOpenSci's internal use cases in mid-to-late 2016, at which point I signed on and then got promptly distracted by academia. Having come back to it in late 2016, I started development in December. This was not intended to compete, still is not intended to compete, and does not compete, with sf, which was first released to CRAN and brought to my attention [after development had been started](https://cran.r-project.org/src/contrib/Archive/sf/). Rather, again, it is an attempt to provide a simple set of utilities that are generally portable.

By portable I do not mean 'it compiles on every operating system', I mean that it compiles on every operating system _and does not require administrator access to install_. This is why the boost::geometry setup was used, rather than GEOS or GDAL which can be difficult to install and work with in workplaces or academic environments where a user does not necessarily have the ability to install system-level libraries. The sf README [notes this requirement directly](https://github.com/edzer/sfr/blob/master/README.md) in the installation section.

In terms of bugs and API stability, I am fully aware that there are bugs and am grateful to you for bringing them to our attention - I will be working on them as soon as possible. I fully expected there to be bugs, which is why the package version is _0_.2.0: as the [semantic versioning specification](http://semver.org/#spec-item-4) notes:

> Major version zero (0.y.z) is for initial development. Anything may change at any time. The public API should not be considered stable.

So, yes; it is not comparable to sfr; this is not an expectation anyone had. It has bugs; this is expected. The former I will clarify in the README and associated documentation when I get home - the latter I will fix when I have time to do so.

In the meantime I must say that I am finding your attitude in this thread unusually and inappropriately combative. As you may know from my other work, I am a strong advocate of the principle that the R community should be a respectful and comfortable place to contribute and develop, and that issues (where they exist) should be raised in a reasonable fashion.

While I am grateful to you for bringing the bugs to my attention, multiple people have contacted me expressing their discomfort with the attitude you have brought to this conversation. Please do your best to strike a more moderate tone, or I will (under the same code of conduct your excellent project uses) "remove, edit, or reject" your comments. They are valuable, but many people are capable of making valuable comments. Knowing that, I choose to restrict myself to dealing with the ones that are respectful, too.

**Comment by edzer** [comment]
Thanks for clarifying the portability issue, @okeyes-r7 : I had interpreted this as issues with installing on Windows or MacOSX, and it is those platforms for which I mentioned that we'd solved issues -- to the extent that R users on those platforms can install binary packages on their own machine. For other platforms (linux only?) it's been a long time since I read reports on users not being able to install GDAL and GEOS, or get it installed by the sys admin, at least on r-sig-geo. Do you hear/see many of those? Remote computing seems to move in a direction where control over the target machine gets easier, afaics.

I apologize for using a sharp tone, and will try to improve. I do appreciate your contributions to open source, and strongly welcome a good R interface to boost::geometry -- it would allow for a nice comparison between the two technologies.

**Comment by okeyes-r7** [comment]
Ahh, gotcha - yeah, I see the point of confusion (and it is definitely Windows being a PITA 99 times out of 100!)

While I can't speak for Scott or the experiences that made this package a need for him, it's certainly something I've encountered at past workplaces (particularly the more security-conscious or security-paranoid ones): my last employer, for example, we did everything on remote servers that were fully puppetised, and so making any changes to the installed system libraries required a full system of code and security review.

I very much appreciate your apology (and am sorry for my reflexive defensiveness at some points in the conversation); agreed that a general interface would be great! I've been thinking a lot about building a more general package people could use or include or things as a recreational project, basically moving the boost::geometry API r-side and using XPtrs to the actual objects. Not sure how feasible or useful it'd be but making it available wouldn't cost anything but my time, so it might be worth a shot.
